name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Setup Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Install dependencies
        run: nix develop --command pnpm install --frozen-lockfile

      - name: Build
        run: nix develop --command pnpm build

      - name: Lint
        run: nix develop --command pnpm lint

      - name: Format check
        run: nix develop --command pnpm check

      - name: Build
        run: nix develop --command pnpm build

      - name: Test
        run: nix develop --command pnpm test

  changeset-check:
    name: Changeset Check
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Setup Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Install dependencies
        run: nix develop --command pnpm install --frozen-lockfile

      - name: Check for changesets
        run: nix develop --command pnpm changeset:status